# Generated by Django 4.2.1 on 2023-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="abdomen_pelvis",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="aspectos_generales",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="cabeza_cuello",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="extremidades",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="neurologico",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="piel_tegumentos",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="torax",
        ),
        migrations.AddField(
            model_name="exploracionfisica",
            name="descripcion_exploracion",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
