# Generated by Django 4.2.1 on 2023-05-09 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="contrasena",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
