# Generated by Django 4.2.1 on 2023-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0003_remove_exploracionfisica_padecimiento_actual_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antecedentes",
            options={
                "verbose_name": "Antecedentes",
                "verbose_name_plural": "2.Antecedentes",
            },
        ),
        migrations.AlterModelOptions(
            name="consulta",
            options={"verbose_name": "Consulta", "verbose_name_plural": "5.Consultas"},
        ),
        migrations.AlterModelOptions(
            name="exploracionfisica",
            options={
                "verbose_name": "Exploracion Física",
                "verbose_name_plural": "4.Exploraciones Físicas",
            },
        ),
        migrations.AlterModelOptions(
            name="historiaclinica",
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "1.Historias Clinicas",
            },
        ),
        migrations.AlterModelOptions(
            name="padecimientoactual",
            options={
                "verbose_name": "Padecimiento Actual",
                "verbose_name_plural": "3.Padecimientos Actuales",
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="curp",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="empleador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="escolaridad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ninguna", "Ninguna"),
                    ("primaria", "Primaria"),
                    ("primaria_t", "Primaria Trunca"),
                    ("secundaria", "Secundaria"),
                    ("secundaria_t", "Secundaria Trunca"),
                    ("preparatoria", "Preparatoria"),
                    ("preparatoria_t", "Preparatoria Trunca"),
                    ("tecnico", "Carrera Tecnica"),
                    ("tecnico_t", "Carrera Tecnica Trunca"),
                    ("licenciatura", "Licenciatura"),
                    ("licenciatura_t", "Licenciatura Trunca"),
                    ("superior", "Superior"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nacionalidad",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre_contacto_emergencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ocupacion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="religion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono_contacto_emergencia",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono_personal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
