# Generated by Django 4.2.1 on 2023-05-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0004_alter_antecedentes_options_alter_consulta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="alergias",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
