# Generated by Django 4.2.1 on 2023-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0005_alter_paciente_alergias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="alergias",
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
