# Generated by Django 4.2.1 on 2023-06-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0007_alter_paciente_alergias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historiaclinica",
            name="notas",
        ),
        migrations.AlterField(
            model_name="paciente",
            name="alergias",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="escolaridad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NINGUNA", "Ninguna"),
                    ("PRIMARIA", "Primaria"),
                    ("PRIMARIA_T", "Primaria Trunca"),
                    ("SECUNDARIA", "Secundaria"),
                    ("SECUNDARIA_T", "Secundaria Trunca"),
                    ("PREPARATORIA", "Preparatoria"),
                    ("PREPARATORIA_T", "Preparatoria Trunca"),
                    ("TECNICO", "Carrera Tecnica"),
                    ("TECNICO_T", "Carrera Tecnica Trunca"),
                    ("LICENCIATURA", "Licenciatura"),
                    ("LICENCIATURA_T", "Licenciatura Trunca"),
                    ("SUPERIOR", "Superior"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("SOLTERO", "Soltero"),
                    ("CASADO", "Casado"),
                    ("UNION_LIBRE", "Union libre"),
                    ("DIVORCIADO", "Divorciado"),
                    ("VIUDO", "Viudo"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="grupo_rh",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("O+", "O+"),
                    ("AB+", "AB+"),
                    ("A-", "A-"),
                    ("B-", "B-"),
                    ("O-", "O-"),
                    ("AB-", "AB-"),
                    ("DESC", "Desconocido"),
                ],
                max_length=4,
            ),
        ),
    ]
