# Generated by Django 4.2.2 on 2023-06-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "medical",
            "0008_remove_historiaclinica_notas_alter_paciente_alergias_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antecedentes",
            options={
                "verbose_name": "Antecedentes",
                "verbose_name_plural": "1.Antecedentes",
            },
        ),
        migrations.AlterModelOptions(
            name="consulta",
            options={"verbose_name": "Consulta", "verbose_name_plural": "4.Consultas"},
        ),
        migrations.AlterModelOptions(
            name="exploracionfisica",
            options={
                "verbose_name": "Exploracion Física",
                "verbose_name_plural": "3.Exploraciones Físicas",
            },
        ),
        migrations.AlterModelOptions(
            name="padecimientoactual",
            options={
                "verbose_name": "Padecimiento Actual",
                "verbose_name_plural": "2.Padecimientos Actuales",
            },
        ),
        migrations.RemoveField(
            model_name="antecedentes",
            name="historia_clinica",
        ),
        migrations.RemoveField(
            model_name="exploracionfisica",
            name="historia_clinica",
        ),
        migrations.RemoveField(
            model_name="padecimientoactual",
            name="historia_clinica",
        ),
        migrations.AddField(
            model_name="antecedentes",
            name="paciente",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical.paciente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exploracionfisica",
            name="paciente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical.paciente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paciente",
            name="fecha_alta",
            field=models.DateField(default="2000-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="padecimientoactual",
            name="paciente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical.paciente",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="HistoriaClinica",
        ),
    ]
