# Generated by Django 4.2.2 on 2023-06-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0009_alter_antecedentes_options_alter_consulta_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("SOLTERO", "Soltero"),
                    ("CASADO", "Casado"),
                    ("UNION_LIBRE", "Union libre"),
                    ("DIVORCIADO", "Divorciado"),
                    ("VIUDO", "Viudo"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
