# Generated by Django 4.2.2 on 2023-06-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0010_alter_paciente_estado_civil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLTERO", "Soltero"),
                    ("CASADO", "Casado"),
                    ("UNION_LIBRE", "Union libre"),
                    ("DIVORCIADO", "Divorciado"),
                    ("VIUDO", "Viudo"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="grupo_rh",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("O+", "O+"),
                    ("AB+", "AB+"),
                    ("A-", "A-"),
                    ("B-", "B-"),
                    ("O-", "O-"),
                    ("AB-", "AB-"),
                    ("DESC", "Desconocido"),
                ],
                default="DESC",
                max_length=4,
            ),
        ),
    ]
