# Generated by Django 4.2.1 on 2023-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0013_alter_antecedentes_ago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="fecha",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="glucosa",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="imc",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="peso",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="presion_arterial",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="saturacion_oxigeno",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="talla",
            field=models.FloatField(default=0),
        ),
    ]
