# Generated by Django 4.2.2 on 2023-06-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0014_alter_exploracionfisica_glucosa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exploracionfisica",
            name="glucosa",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="imc",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="peso",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="saturacion_oxigeno",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exploracionfisica",
            name="talla",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
